spring:
  application:
    name: request-processor

  datasource:
    url: jdbc:postgresql://localhost:5432/processor_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

outbox:
  batch-size: 50
  delay-ms: 1000
  max-attempts: 5

logging:
  level:
    com.borscheva.spring.rest.requestprocessor: INFO
    org.springframework.kafka: WARN